# Generated by Django 4.0.2 on 2022-02-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('شقة', 'شقة'), ('محل', 'محل'), ('عمارة', 'عمارة'), ('فيلا', 'فيلا'), ('شالية', 'شالية'), ('دولكس', 'دولكس'), ('استوديو', 'استوديو')], default='شقة', max_length=20)),
                ('forwhat', models.CharField(choices=[('شقة', 'شقة'), ('محل', 'محل'), ('عمارة', 'عمارة'), ('فيلا', 'فيلا'), ('شالية', 'شالية'), ('دولكس', 'دولكس'), ('استوديو', 'استوديو')], default='بيع', max_length=20)),
                ('area', models.IntegerField()),
                ('rooms_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='3', max_length=20)),
                ('price', models.IntegerField()),
                ('bathroom', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Description', models.TextField(blank=True, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
