# Generated by Django 4.0.2 on 2022-03-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_alter_building_bathroom_alter_building_forwhat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='bathroom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='rooms_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
