# Generated by Django 4.0.2 on 2022-03-02 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_rename_description_building_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='rooms_number',
            new_name='rooms',
        ),
    ]
