# Generated by Django 4.0.2 on 2022-04-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_rename_photos_building_image1_building_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='image1',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image5',
        ),
    ]
